development:
  adapter: postgresql
  encoding: utf8
  database: wishlister_development
  username: postgres
  password: 123456
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: wishlister_test
  username: postgres
  password: 123456
  host: localhost
